import CaptionGeneratorTool from "@/components/CaptionGeneratorTool";
import Link from "next/link";
import { ArrowLeft, Sparkles, Moon, Feather, Camera } from "lucide-react";
import { FaInstagram } from "react-icons/fa6";

export const metadata = {
  title: "Aesthetic Captions for Instagram — AI Aesthetic Caption Generator | Entry",
  description:
    "Generate dreamy, poetic, aesthetic captions for Instagram. AI-powered aesthetic caption generator — soft, visually evocative, mood-driven captions with hashtags.",
  keywords: [
    "aesthetic captions for instagram",
    "aesthetic instagram captions",
    "soft aesthetic captions",
    "dreamy instagram captions",
    "poetic instagram captions",
    "aesthetic caption generator",
    "aesthetic captions AI",
    "aesthetic quotes for instagram",
    "moody captions instagram",
    "vsco captions",
  ],
  alternates: { canonical: "https://entry-azure.vercel.app/caption-generator/aesthetic-captions" },
  openGraph: {
    title: "Aesthetic Captions for Instagram — AI Generator | Entry",
    description:
      "Dreamy, poetic, visually evocative captions generated by AI. Free aesthetic caption generator for Instagram.",
    url: "https://entry-azure.vercel.app/caption-generator/aesthetic-captions",
    siteName: "Entry",
    images: [
      {
        url: "https://entry-azure.vercel.app/android-chrome-512x512.png",
        width: 512,
        height: 512,
      },
    ],
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Aesthetic Instagram Caption Generator | Entry",
    description:
      "Generate soft, dreamy, aesthetic captions for Instagram with AI. Free, no signup.",
    images: ["https://entry-azure.vercel.app/android-chrome-512x512.png"],
  },
};

const aestheticVibes = [
  {
    icon: Moon,
    title: "Dreamy & Poetic",
    desc: "Captions that feel like a soft watercolor painting put into words.",
  },
  {
    icon: Camera,
    title: "Visually Evocative",
    desc: "Language that paints a picture and complements your aesthetic photography.",
  },
  {
    icon: Feather,
    title: "Soft & Intentional",
    desc: "Every word is chosen for feeling — slow, peaceful, and beautifully minimal.",
  },
];

const aestheticExamples = [
  "golden hour felt like a reminder to slow down",
  "there's something about mornings that feel like a fresh page",
  "collecting moments, not things",
  "soft light and softer days",
];

export default function AestheticCaptionsPage() {
  return (
    <div className="min-h-screen bg-[var(--background)] font-playfair text-[var(--foreground)]">
      {/* ── Hero ── */}
      <header className="container mx-auto px-6 pt-16 pb-12">
        <Link
          href="/caption-generator"
          className="inline-flex items-center gap-2 text-[var(--muted)] hover:text-[var(--accent)] transition-colors mb-12 font-bold uppercase tracking-widest text-xs"
        >
          <ArrowLeft size={14} /> All Platforms
        </Link>

        <div className="w-full flex flex-col items-center justify-center mb-14 text-center">
          {/* Aesthetic icon cluster */}
          <div className="flex items-center gap-3 mb-6">
            <div
              className="w-12 h-12 rounded-xl flex items-center justify-center"
              style={{
                background:
                  "linear-gradient(135deg, #f09433 0%, #e6683c 25%, #dc2743 50%, #cc2366 75%, #bc1888 100%)",
              }}
            >
              <FaInstagram size={24} color="white" />
            </div>
            <div className="w-12 h-12 rounded-xl flex items-center justify-center bg-[var(--card)]/20 border border-[var(--border)]">
              <Sparkles size={22} className="text-[var(--accent)]" />
            </div>
          </div>

          <div className="flex items-center justify-center gap-3 mb-5">
            <Sparkles className="w-5 h-5 text-[var(--accent)]" />
            <p className="text-[13px] font-bold uppercase tracking-[0.4em] text-[var(--accent)] leading-none">
              Aesthetic · AI Captions
            </p>
          </div>

          <h1 className="text-4xl md:text-6xl font-bold tracking-tight leading-[0.9] mb-5">
            Aesthetic
            <br />
            <span className="text-[var(--accent)]">Caption Generator</span>
            <span className="text-[var(--muted)]">.</span>
          </h1>

          <p className="text-base md:text-lg text-[var(--muted)] leading-relaxed italic opacity-80 max-w-2xl">
            For the golden-hour moments, the slow Sunday mornings, the fog-over-the-mountains shots.
            Generate dreamy, poetic captions that match your aesthetic perfectly.
          </p>
        </div>

        {/* Aesthetic vibe cards */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 max-w-3xl mx-auto">
          {aestheticVibes.map(({ icon: Icon, title, desc }) => (
            <div
              key={title}
              className="rounded-2xl border border-[var(--border)] p-5 bg-[var(--card)]/10 flex flex-col gap-2"
            >
              <Icon size={17} className="text-[var(--accent)] opacity-80" />
              <p className="text-sm font-bold text-[var(--foreground)]">{title}</p>
              <p className="text-xs text-[var(--muted)] leading-snug">{desc}</p>
            </div>
          ))}
        </div>
      </header>

      {/* ── Example aesthetic captions preview ── */}
      <section className="container mx-auto px-6 pb-10">
        <div className="max-w-3xl mx-auto">
          <p className="text-xs font-bold uppercase tracking-[0.35em] text-[var(--muted)] mb-4 text-center">
            The kind of captions you'll get
          </p>
          <div className="flex flex-wrap justify-center gap-3">
            {aestheticExamples.map((ex) => (
              <span
                key={ex}
                className="text-sm italic text-[var(--muted)] px-4 py-2 rounded-full border border-[var(--border)] bg-[var(--card)]/10"
              >
                "{ex}"
              </span>
            ))}
          </div>
        </div>
      </section>

      {/* ── Tool (pre-selected: Instagram + Aesthetic mood) ── */}
      <main className="container mx-auto px-6 pb-24">
        <div className="max-w-3xl mx-auto">
          <div className="bg-[var(--card)]/10 border border-[var(--border)] rounded-[40px] p-8 md:p-12 shadow-sm">
            <CaptionGeneratorTool defaultPlatform="instagram" defaultMood="aesthetic" />
          </div>
        </div>
      </main>

      {/* ── Contextual content ── */}
      <section className="container mx-auto px-6 pb-24">
        <div className="max-w-3xl mx-auto">
          <div className="rounded-2xl border border-[var(--border)] bg-[var(--card)]/10 p-8 space-y-4">
            <h2 className="text-2xl font-bold text-[var(--foreground)]">
              What Makes an Aesthetic Caption?
            </h2>
            <p className="text-sm text-[var(--muted)] leading-relaxed">
              Aesthetic captions aren't just pretty words — they create a feeling. They slow the
              reader down, make them pause, and connect emotionally with the image. The best
              aesthetic captions use sensory language, avoid clichés, and feel genuine rather than
              performative.
            </p>
            <p className="text-sm text-[var(--muted)] leading-relaxed">
              Entry's AI is tuned for the aesthetic mood specifically: short, lyrical sentences,
              soft imagery, and a contemplative tone. The hashtags are curated for the aesthetic
              niche — balancing reach with community relevance.
            </p>
          </div>
        </div>
      </section>
    </div>
  );
}
