import mongoose from "mongoose";

/**
 * MoodAnalytics Model
 *
 * Weekly mood aggregation per user.
 * Populated by a server-side cron or triggered on diary stats fetch.
 * The aiInsight field is generated by Groq on demand (max once per week).
 */
const moodAnalyticsSchema = new mongoose.Schema(
  {
    authorId: {
      type: String,
      required: true,
      index: true,
    },

    // ISO week start date (Monday, YYYY-MM-DD)
    weekStart: {
      type: String,
      required: true,
    },

    // Count of each mood recorded this week
    moodCounts: {
      happy: { type: Number, default: 0 },
      calm: { type: Number, default: 0 },
      anxious: { type: Number, default: 0 },
      sad: { type: Number, default: 0 },
      excited: { type: Number, default: 0 },
      neutral: { type: Number, default: 0 },
    },

    // AI-generated emotional summary + productivity insight for this week
    // Generated by Groq using entry titles + moods (never decrypted content)
    aiInsight: {
      type: String,
      default: null,
    },

    // Whether AI insight was generated this week
    insightGeneratedAt: {
      type: Date,
      default: null,
    },
  },
  {
    timestamps: true,
  }
);

// Compound unique index — one record per user per week
moodAnalyticsSchema.index({ authorId: 1, weekStart: 1 }, { unique: true });

const MoodAnalytics =
  mongoose.models.MoodAnalytics ||
  mongoose.model("MoodAnalytics", moodAnalyticsSchema);

export default MoodAnalytics;
